# Generated by Django 5.2.1 on 2025-05-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_review_review_user_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
    ]
