# Generated by Django 5.2.1 on 2025-07-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_watchlist_avg_rating_watchlist_number_of_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='streamplatform_images/'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watchlist_images/'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='storyLine',
            field=models.TextField(max_length=500),
        ),
    ]
