# Generated by Django 5.2.1 on 2025-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0010_actors_starcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
