# Generated by Django 5.2.1 on 2025-07-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0012_genre_imagelist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='watchlist_app.watchlist'),
        ),
    ]
